# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test, Build and Publish
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20.0'
        id: go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          ( cd request; go test -race ./... )
          ( cd core; go test -race  ./... )
          ( cd coremain; go test -race ./... )

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coredns
          path: coredns

  test-plugins:
    name: Test Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20.0'
        id: go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: ( cd plugin; go test -race ./... )

  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20.0'
        id: go

      - name: Build
        run: make

      - name: Zip Build
        run: |
          tar -cz coredns -f coredns_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tgz
          sha256sum coredns_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tgz > coredns_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tgz.sha256
          ls -lah

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            coredns_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tgz
            coredns_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tgz.sha256
